<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
//path application/third_party/Excel.php

class Theworld  {
   
    public function the_origin($origin='null'){
        	$the_origin = 
		[
			"Afghanistan",
			"Albania",
			"Algeria",
			"Andorra",
			"Angola",
			"Antigua and Barbuda",
			"Argentina",
			"Armenia",
			"Australia",
			"Austria",
			"Azerbaijan",
			"Bahamas",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgium",
			"Belize",
			"Benin",
			"Bhutan",
			"Bolivia",
			"Bosnia and Herzegovina",
			"Botswana",
			"Brazil",
			"Brunei",
			"Bulgaria",
			"Burkina Faso",
			"Burundi",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Cape Verde",
			"Central African Republic",
			"Chad",
			"Chile",
			"China",
			"Colombi",
			"Comoros",
			"Congo (Brazzaville)",
			"Congo",
			"Costa Rica",
			"Cote d'Ivoire",
			"Croatia",
			"Cuba",
			"Cyprus",
			"Czech Republic",
			"Denmark",
			"Djibouti",
			"Dominica",
			"Dominican Republic",
			"East Timor (Timor Timur)",
			"Ecuador",
			"Egypt",
			"El Salvador",
			"Equatorial Guinea",
			"Eritrea",
			"Estonia",
			"Ethiopia",
			"Fiji",
			"Finland",
			"France",
			"Gabon",
			"Gambia, The",
			"Georgia",
			"Germany",
			"Ghana",
			"Greece",
			"Grenada",
			"Guatemala",
			"Guinea",
			"Guinea-Bissau",
			"Guyana",
			"Haiti",
			"Honduras",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran",
			"Iraq",
			"Ireland",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jordan",
			"Kazakhstan",
			"Kenya",
			"Kiribati",
			"Kingdom of Saudi Arabia",
			"Korea, North",
			"Korea, South",
			"Kuwait",
			"Kyrgyzstan",
			"Laos",
			"Latvia",
			"Lebanon",
			"Lesotho",
			"Liberia",
			"Libya",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Macedonia",
			"Madagascar",
			"Malawi",
			"Malaysia",
			"Maldives",
			"Mali",
			"Malta",
			"Marshall Islands",
			"Mauritania",
			"Mauritius",
			"Mexico",
			"Micronesia",
			"Moldova",
			"Monaco",
			"Mongolia",
			"Morocco",
			"Mozambique",
			"Myanmar",
			"Namibia",
			"Nauru",
			"Nepal",
			"Netherlands",
			"New Zealand",
			"Nicaragua",
			"Niger",
			"Nigeria",
			"Norway",
			"Oman",
			"Pakistan",
			"Palau",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Qatar",
			"Romania",
			"Russia",
			"Rwanda",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Vincent",
			"Samoa",
			"San Marino",
			"Sao Tome and Principe",
			"Saudi Arabia",
			"Senegal",
			"Serbia and Montenegro",
			"Seychelles",
			"Sierra Leone",
			"Singapore",
			"Slovakia",
			"Slovenia",
			"Solomon Islands",
			"Somalia",
			"South Africa",
			"Spain",
			"Sri Lanka",
			"Sudan",
			"Suriname",
			"Swaziland",
			"Sweden",
			"Switzerland",
			"Syria",
			"Taiwan",
			"Tajikistan",
			"Tanzania",
			"Thailand",
			"Togo",
			"Tonga",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Turkmenistan",
			"Tuvalu",
			"Uganda",
			"Ukraine",
			"United Arab Emirates",
			"United Kingdom",
			"United States",
			"Uruguay",
			"Uzbekistan",
			"Vanuatu",
			"Vatican City",
			"Venezuela",
			"Vietnam",
			"Yemen",
			"Zambia",
			"Zimbabwe"
		];
        return $the_origin;
    }
    
     public function the_race($race='null'){
        $the_race=
	[
		"Afghan",
		"Albanian",
		"Algerian",
		"American",
		"Andorran",
		"Angolans",
		"Argentine",
		"Armenian",
		"Aromanian",
		"Aruban",
		"Australian",
		"Austrian",
		"Azeri",
		"Bahamian",
		"Bahraini",
		"Bangladeshi",
		"Barbadian",
		"Belarusian",
		"Belgian",
		"Belizean",
		"Bermudian",
		"Boer",
		"Bosniak",
		"Brazilian",
		"Breton",
		"British",
		"British Virgin Islander",
		"Bulgarian",
		"Macedonian Bulgarian",
		"Burkinabè",
		"Burundian",
		"Cambodian",
		"Cameroonians",
		"Canadian",
		"Catalan",
		"Cape Verdean",
		"Chadian",
		"Chilean",
		"Chinese",
		"Colombian",
		"Comorian",
		"Congolese",
		"Croatian",
		"Cuban",
		"Cypriot",
		"Turkish Cypriot",
		"Czech",
		"Dane",
		"Dominican (Republic)",
		"Dominican (Commonwealth)",
		"Dutch",
		"East Timorese",
		"Ecuadorian",
		"Egyptian",
		"Emirati",
		"English",
		"Eritrean",
		"Estonian",
		"Ethiopians",
		"Faroese",
		"Finn",
		"Finnish Swedish",
		"Fijian",
		"Filipino",
		"French citizen",
		"Georgians",
		"German",
		"Baltic German",
		"Ghanaian",
		"Gibraltar",
		"Greek",
		"Greek Macedonian",
		"Grenadian",
		"Guatemalan",
		"Guianese (French)",
		"Guinean",
		"Guinea-Bissau national",
		"Guyanese",
		"Haitian",
		"Honduran",
		"Hong Kong",
		"Hungarian",
		"Icelander",
		"Indian",
		"Indonesian",
		"Iranian (Persian)",
		"Arab",
		"Irish",
		"Israeli",
		"Italian",
		"Ivoirian",
		"Jamaican",
		"Japanese",
		"Jordanian",
		"Kazakh",
		"Kenyan",
		"Korean",
		"Kosovo Albanian",
		"Kurd",
		"Kuwaiti",
		"Lao",
		"Latvian",
		"Lebanese",
		"Liberian",
		"Libyan",
		"Liechtensteiner",
		"Lithuanian",
		"Luxembourger",
		"Macedonian",
		"Malaysian",
		"Malawian",
		"Maldivian",
		"Malian",
		"Maltese",
		"Manx",
		"Mauritian",
		"Mexican",
		"Moldovan",
		"Moroccan",
		"Mongolian",
		"Montenegrin",
		"Namibian",
		"Nepalese",
		"New Zealander",
		"Nicaraguan",
		"Nigerien",
		"Nigerian",
		"Norwegian",
		"Pakistani",
		"Palauan",
		"Palestinian",
		"Panamanian",
		"Papua New Guinean",
		"Paraguayan",
		"Peruvian",
		"Pole",
		"Portuguese",
		"Puerto Rican",
		"Quebecer",
		"Réunionnai",
		"Romanian",
		"Russians",
		"Baltic Russian",
		"Rwandan",
		"Salvadoran",
		"São Tomé and Príncipe",
		"Saudi",
		"Scot",
		"Senegalese",
		"Serb",
		"Sierra Leonean",
		"Singaporean",
		"Slovak",
		"Slovene",
		"Somalis",
		"South African",
		"Spaniard",
		"Sri Lankan",
		"St Lucian",
		"Sudanese",
		"Surinamese",
		"Swedes",
		"Swiss",
		"Syrians",
		"Taiwanese",
		"Tanzanian",
		"Thai",
		"Tibetan",
		"Tobagonian",
		"Trinidadian",
		"Tunisian",
		"Turk",
		"Tuvaluan",
		"Ugandan",
		"Ukrainian",
		"Uruguayan",
		"Uzbek",
		"Vanuatuan",
		"Venezuelan",
		"Vietnamese",
		"Welsh",
		"Yemeni",
		"Zambian",
		"Zimbabwean"
	];
    
    return $the_race;
    
    }
	
	public function check_val($value,$def=''){
		$val=($value)?$value:$def;
		return $val;
	}
    
}